export const Pelicula = {
  id: null,
  nombre: '',
  titulo_original: '',
  sinopsis: '',
  genero: '',
  duracion: '',
  clasificacion: '',
  idioma: 'Español',
  formato: '2D',
  poster_url: '',
  director: '',
  reparto: '',
  anio: null,
  pais: '',
  trailer_url: '',
  estreno: false,
  activa: true,
  emoji: '🎬',
  fecha_desde: '',
  fecha_hasta: '',
};
